namespace SaveAPI;

public enum CustomTrackedStats
{
	EXAMPLE_STATS,
	TITAN_KIN_KILLED,
	BEHOLSTER_KILLS,
	MINEFLAYER_KILLS,
	DOOR_LORD_KILLS,
	CHARMED_ENEMIES_KILLED,
	JAMMED_CHESTS_OPENED,
	RUSTY_ITEMS_PURCHASED,
	RUSTY_ITEMS_STOLEN,
	IRONSIDE_ITEMS_PURCHASED,
	IRONSIDE_ITEMS_STOLEN,
	BOOMHILDR_ITEMS_PURCHASED,
	BOOMHILDR_ITEMS_STOLEN,
	CHANCELOT_MONEY_SPENT,
	TIMES_GAMBLED,
	GAMBLING_WINNINGS,
	BEGGAR_TOTAL_DONATIONS,
	BEGGAR_REPEAT_TARGET,
	BEGGAR_REPEAT_CURRENT,
	DOUG_ITEMS_PURCHASED
}
